# Generated by Django 2.2.2 on 2019-06-16 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trash',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_seen', models.DateField(verbose_name='Last Seen')),
                ('was_there', models.BooleanField(default=False)),
                ('trash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Trash')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('trash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Trash')),
            ],
        ),
        migrations.AddField(
            model_name='trash',
            name='flair',
            field=models.ManyToManyField(to='main_app.Flair'),
        ),
    ]
