# Generated by Django 2.2.2 on 2019-06-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190616_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seen',
            name='time_seen',
            field=models.DateTimeField(verbose_name='Last Seen'),
        ),
    ]
